# Generated by Django 5.0.7 on 2024-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_waitlistentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
